const generateRandomSub = require('../../../util/generateRandomSub');

const TABLE_NAME = 'users';
exports.seed = (knex, Promise) => {
  knex(TABLE_NAME)
    .del()
    .then(() => {
      knex(TABLE_NAME).insert([
        {
          // newid: 1
          // id: '22',
          sub: 'auth0|5e5930485174b61780a19141',
          email: 'katiefelten+new2@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582929414548_photo.jpg',
          created_at: '2020-02-28 12:45:20.244776-06',
          location: 'Atlanta, Georgia',
          mini_bio:
            'Some bears cannot bear to not bear as long as they intended to bear',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '43553',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 1,
          full_text_weighted: "'katiefelten':1A 'new2@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 2
          // id: '1',
          sub: 'auth0|5e5881c89848f5106d97a36b',
          email: 'mtourjoman01@hotmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1589798285321_photo.jpg',
          created_at: '2020-02-27 21:14:54.904831-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'mtourjoman01@hotmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 3
          // id: '13',
          sub: 'auth0|5e593559e467971787ca18ec',
          email: 'bri+org1@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582920804744_photo.jpg',
          created_at: '2020-02-28 10:02:04.890947-06',
          location: 'Miami, FL',
          mini_bio: 'An organized organization',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '111-222-3333',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'bri':1A 'org1@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 4
          // id: '43',
          sub: 'auth0|5daa36cb3c63c40d6ba2a5dd',
          email: 'katiefelten@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-02 11:42:22.195777-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiefelten@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 5
          // id: '10',
          sub: 'auth0|5e588b7000a24e10679261dd',
          email: 'bri@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582863892301_photo.jpg',
          created_at: '2020-02-27 22:23:03.342097-06',
          location: 'Nashville, TN',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'bri@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 6
          // id: '11',
          sub: 'auth0|5e4c0d8052b18b0e80549f6d',
          email: 'katiefelten+neworg@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582902946259_photo.jpg',
          created_at: '2020-02-28 09:11:32.162465-06',
          location: 'Miami, Florida',
          mini_bio: 'Saving all the doggos',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiefelten':1A 'neworg@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 7
          // id: '18',
          sub: 'auth0|5e5947905174b61780a1b3f9',
          email: 'jasminekh96@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582920300699_photo.jpg',
          created_at: '2020-02-28 11:02:20.668197-06',
          location: 'New York',
          mini_bio: 'Save the sloths',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 't',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jasminekh96@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 8
          // id: '32',
          sub: 'auth0|5e5977cae665ac0d5558a6c1',
          email: 'gg@gg.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582921804886_photo.jpg',
          created_at: '2020-02-28 14:28:16.895297-06',
          location: 'Dfg',
          mini_bio: 'Sdfg',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'gg@gg.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 9
          // id: '45',
          sub: 'auth0|5e5d55c6df5f5a0d51d36932',
          email: 'bri+org2@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583175309992_photo.jpg',
          created_at: '2020-03-02 12:54:39.717019-06',
          location: '123 Main Street',
          mini_bio: 'Hey',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '111-222-3333',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'bri':1A 'org2@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 10
          // id: '15',
          sub: 'auth0|5e5940555174b61780a1a9c4',
          email: 'arizephyr123@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582908619498_photo.jpg',
          created_at: '2020-02-28 10:31:28.080879-06',
          location: 'California',
          mini_bio: 'Hi! I want to save animals.',
          species_and_habitats: '',
          twitter: '',
          facebook: 'https://sdadsds',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'arizephyr123@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 11
          // id: '19',
          sub: 'auth0|5e59499de467971787ca364d',
          email: 'jasminekh@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1582910650751_photo.jpg',
          created_at: '2020-02-28 11:23:50.985625-06',
          location: 'New York',
          mini_bio: 'Save the sloths.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '5555555555',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jasminekh@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 12
          // id: '69',
          sub: '12dfggggdfghfghnfg2dfg14354123',
          email: 'bhsfgghffh@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-03 19:38:48.101555-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'bhsfgghffh@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 13
          // id: '37',
          sub: '12564684214354123',
          email: 'blah@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-02-28 14:39:40.797434-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'blah@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 14
          // id: '38',
          sub: '12564684dfgdfg214354123',
          email: 'blah@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-02-28 14:40:11.118652-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'blah@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 15
          // id: '41',
          sub: '12564684dfgdfg2dfg14354123',
          email: 'blah@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-02-28 14:40:47.627323-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'blah@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 16
          // id: '16',
          sub: 'auth0|5e58872300a24e1067925dc4',
          email: 'brianna.workman@hotmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583172067999_photo.jpg',
          created_at: '2020-02-28 10:55:09.053012-06',
          location: 'Nashville, TN',
          mini_bio: 'Dogs',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'brianna.workman@hotmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 17
          // id: '65',
          sub: 'auth0|5e5ea903a09e3f0d6e3a7d72',
          email: 'eight@eight.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583262263411_photo.jpg',
          created_at: '2020-03-03 13:03:17.741653-06',
          location: 'Philadelphia, pa',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: 'Asdf',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'eight@eight.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 18
          // id: '27',
          sub: 'auth0|5e5972c5d977310d4ff62e65',
          email: 'jasmine@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583256645987_photo.png',
          created_at: '2020-02-28 14:11:49.336477-06',
          location: 'Australia ',
          mini_bio: 'Save the sloths. ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '63155555555',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jasmine@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 19
          // id: '71',
          sub: 'auth0|5e28ceb614294a0db54dcac8',
          email: 'ataneja@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-07 15:27:42.442908-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'ataneja@ucsd.edu':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 20
          // id: '64',
          sub: 'auth0|5e5e9b880783a50da73e90e1',
          email: 'seven@seven.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583261659362_photo.jpg',
          created_at: '2020-03-03 12:51:03.498802-06',
          location: 'Philadelphia, PA',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: 'Sdf',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'seven@seven.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 21
          // id: '67',
          sub: '12564684dfdfgdfggdfg2dfg14354123',
          email: 'blahhh@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-03 19:16:42.349801-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'blahhh@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 22
          // id: '68',
          sub: '12564684dfdfgdfgdfggdfg2dfg14354123',
          email: 'blahh6h@blah.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-03 19:18:25.601089-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'blahh6h@blah.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 23
          // id: '2',
          sub: 'auth0|5e58876b00a24e1067925e14',
          email: 'mtourjoman0@gmail.com',
          profile_image:
            'https://keycontest.s3.amazonaws.com/files/1583550187015_photo.png',
          created_at: '2020-02-27 21:27:43.316296-06',
          location: 'California',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 't',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'mtourjoman0@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 24
          // id: '47',
          sub: 'auth0|5e5d94f3cd78360d6f838a4e',
          email: 'all197@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-02 17:21:33.425836-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'all197@ucsd.edu':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 25
          // id: '58',
          sub: 'google-oauth2|101155844052758297714',
          email: 'smhariha@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-02 17:23:39.896142-06',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'smhariha@ucsd.edu':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 26
          // id: '66',
          sub: 'auth0|5e5ea319a09e3f0d6e3a6831',
          email: 'a22@g.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-03 13:23:31.210304-06',
          location: 'Dfdsdf',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: 'Dfsdf',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'a22@g.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 27
          // id: '70',
          sub: 'auth0|5e6307a9f7feca0d3492faf6',
          email: 'katiefelten+test2@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1583551728292_photo.png',
          created_at: '2020-03-06 20:32:39.2586-06',
          location: 'Miami, Florida',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiefelten':1A 'test2@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 28
          // id: '99',
          sub: 'auth0|5e41e4666922b70f18a7b6b0',
          email: 'sumeetbansal@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-26 16:51:28.080983-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'sumeetbansal@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 29
          // id: '59',
          sub: 'auth0|5e5d99699a67390d46dd59bd',
          email: 'katiefelten@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586291675655_photo.jpg',
          created_at: '2020-03-02 17:40:36.631135-06',
          location: 'Atlanta, GA',
          mini_bio:
            'Love doggos, specifically the handsome ones with good fluff.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiefelten@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 30
          // id: '127',
          sub: 'auth0|5e8e13ef2fae670c8e56cf05',
          email: 'development+dl@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586369603266_photo.png',
          created_at: '2020-04-08 13:12:14.609562-05',
          location: 'Badan, Philippines',
          mini_bio:
            'Current Ph.D. candidate at Scripps researching coral reef acidification?, surfer and doggo parent to Max ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'dl@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 31
          // id: '103',
          sub: 'auth0|5e67e7bbc9b2060d888076c0',
          email: 'jessnovak2@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-04-01 10:50:08.340758-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jessnovak2@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 32
          // id: '118',
          sub: 'auth0|5e66c1c345d0e50d366359b1',
          email: 'ataneja@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-04-04 14:17:08.295704-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'ataneja@ucsd.edu':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 33
          // id: '86',
          sub: 'auth0|5e78dab906f9560c7f8b7e7b',
          email: 'moreira.kd@outlook.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-23 14:08:54.040281-05',
          location: 'Orlando, FL',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'moreira.kd@outlook.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 34
          // id: '87',
          sub: 'auth0|5e79093fe2cfa70c677b0793',
          email: 'katiesup@mail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-23 14:27:14.980407-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiesup@mail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 35
          // id: '88',
          sub: 'auth0|5e790e14251af90c519b7cf4',
          email: 'katiesup3@mail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-23 14:29:39.32697-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiesup3@mail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 36
          // id: '89',
          sub: 'auth0|5e790eb8e2cfa70c677b1c43',
          email: 'katiesup44@mail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-23 14:32:22.609466-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiesup44@mail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 37
          // id: '90',
          sub: 'auth0|5e790f1fe2cfa70c677b1dee',
          email: 'katiesup55@mail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1584996718316_photo.png',
          created_at: '2020-03-23 14:34:13.949103-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiesup55@mail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 38
          // id: '91',
          sub: 'auth0|5e729c7c87e1e60ca87590ea',
          email: 'robertdstepanov@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-23 15:58:00.968281-05',
          location: 'St Pete',
          mini_bio: 'I like pina coladas and getting caught in the rain.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'robertdstepanov@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 39
          // id: '44',
          sub: 'auth0|5e5d4ad06e8fe60d6a974164',
          email: 'katiefelten+org@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1584999030432_photo.jpg',
          created_at: '2020-03-02 12:09:31.030852-06',
          location: 'Atlanta, GA',
          mini_bio: 'We have been supporting orange fluffy boys since 2017. ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '1',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'katiefelten':1A 'org@gmail.com':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 40
          // id: '134',
          sub: 'auth0|5e68fd5a0765890dc34f3f50',
          email: 'alex.oddlogic@gmail.com ',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1587667916002_photo.jpg',
          created_at: '2020-04-13 12:01:45.076072-05',
          location: 'Philadelphia',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'alex.oddlogic@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 41
          // id: '93',
          sub: 'auth0|5e7a9b3118dc2d0c6a5f7e6f',
          email: 'dacp12+conservationist@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-24 19:19:56.832312-05',
          location: '123 Main St',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18001234567',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'conservationist@ucsd.edu':2A 'dacp12':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 42
          // id: '94',
          sub: 'auth0|5e73b955b3a9bc0cb061059c',
          email: 'gohorelalex@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-25 11:29:31.859186-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'gohorelalex@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 43
          // id: '180',
          sub: 'auth0|5ec30be67d697c0c718ea6a6',
          email: 'test@g.cv',
          profile_image: '',
          created_at: '2020-05-18 17:28:17.815508-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'test@g.cv':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 44
          // id: '98',
          sub: 'auth0|5e5ea161dc14a00d6b3e283a',
          email: 'development+dss@keyconservation.org',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-26 16:01:13.335943-05',
          location: 'Mojave Desert, California',
          mini_bio:
            'Established in 1986, we are now the leading research facility for all spiders within the Mojave Desert region. ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18004567845',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'dss@keyconservation.org':2A",
          accepting_help_requests: 't',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 45
          // id: '129',
          sub: 'auth0|5e5f4a85ce9c820d5e1d8ca7',
          email: 'development+gtf@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586371512850_photo.png',
          created_at: '2020-04-08 13:40:21.125111-05',
          location: 'Mumbai, India',
          mini_bio:
            'We are a collaboration of tiger researchers and organizations who are working to protect and preserve tiger populations globally.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18007783456',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'gtf@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 46
          // id: '102',
          sub: 'auth0|5e265d565256fc0ea8ca43d2',
          email: 'thomasligreat11@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-27 17:17:44.76783-05',
          location: 'Miami, Florida',
          mini_bio: 'I am a test account',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'thomasligreat11@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 47
          // id: '130',
          sub: 'auth0|5e5f4e1288ec170d6b90440a',
          email: 'development+oc@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586374584762_photo.png',
          created_at: '2020-04-08 14:34:54.00561-05',
          location: 'Alice Springs, Australia',
          mini_bio:
            'We protect and restore the habitats and species of the Australian Outback. ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18005556677',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'oc@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 48
          // id: '137',
          sub: 'auth0|5ea7192b1cc1ac0c146b2e87',
          email: 'test@test.gov',
          profile_image: '',
          created_at: '2020-04-28 11:42:33.970122-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'test@test.gov':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 49
          // id: '135',
          sub: 'blahdumblee',
          email: 'tralala@lala.tra',
          profile_image: '',
          created_at: '2020-04-13 17:38:05.64838-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'tralala@lala.tra':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 50
          // id: '138',
          sub: 'auth0|5eacc0ff1cc1ac0c147c4cc4',
          email: 'email@lambda.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-01 19:38:51.935-05',
          location: 'San Diego',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'email@lambda.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 51
          // id: '147',
          sub: 'auth0|5eb1dfc21cc1ac0c14894227',
          email: 'afia@g.com',
          profile_image: '',
          created_at: '2020-05-05 16:51:21.353609-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'afia@g.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 52
          // id: '121',
          sub: 'auth0|5e5f4261ce9c820d5e1d7e16',
          email: 'nlapolla@ucsd.edu',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-04-08 00:01:37.981468-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'nlapolla@ucsd.edu':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 53
          // id: '92',
          sub: 'auth0|5e620f03292a730d383d1436',
          email: 'dac012+supporter@ucsd.edu',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1590347278340_photo.png',
          created_at: '2020-03-24 15:41:14.053248-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'dac012':1A 'supporter@ucsd.edu':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 54
          // id: '95',
          sub: 'auth0|5e5ef901ce9c820d5e1cd9d7',
          email: 'development+wrc@keyconservation.org',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-26 11:11:06.387362-05',
          location: 'Jackson, Wyoming',
          mini_bio:
            'We work to protect and rehabilitate raptors within the Greater Yellowstone Ecosystem.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18001234567',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'wrc@keyconservation.org':2A",
          accepting_help_requests: 't',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 55
          // id: '131',
          sub: 'auth0|5e5f51dd88ec170d6b904aa0',
          email: 'development+ca@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586376075731_photo.png',
          created_at: '2020-04-08 14:59:54.571868-05',
          location: 'Raja Ampat, Indonesia',
          mini_bio:
            'Our organization is located within the beautiful Coral Triangle at the intersection of the Indian and Pacific Ocean. We work to protect one of the wor',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18005678938',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'ca@keyconservation.org':2A 'develop':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 56
          // id: '132',
          sub: 'auth0|5e5f545088ec170d6b904f6b',
          email: 'development+ufwg@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586378280725_photo.png',
          created_at: '2020-04-08 15:36:36.100582-05',
          location: 'Santiago, Chile',
          mini_bio:
            'Our mission is to significantly increase the number and impact of urban trees in Santiago. We work with local community groups to plant and care for t',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '19849278',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'ufwg@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 57
          // id: '133',
          sub: 'auth0|5e5f56346a0dce0d658f5172',
          email: 'development+ban@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1586378882572_photo.png',
          created_at: '2020-04-08 15:46:26.300214-05',
          location: 'Surrey, United Kingdom',
          mini_bio:
            'Fighting to protect the habitats that bats need to survive and to promote a healthy and sustainable environment. ',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '32444',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'ban@keyconservation.org':2A 'develop':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 58
          // id: '97',
          sub: 'auth0|5e5e9f7adc14a00d6b3e21bc',
          email: 'development+ewf@keyconservation.org',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-03-26 11:47:30.052788-05',
          location: 'Flamingo, Florida',
          mini_bio:
            'We have been working to protect and restore wildlife within Everglades National Park for the past 20 years.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '18003456789',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'ewf@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 59
          // id: '126',
          sub: 'auth0|5e8e13212fae670c8e56cbe2',
          email: 'development+ms@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1590769185901_photo.png',
          created_at: '2020-04-08 13:08:55.445827-05',
          location: 'Belo Horizonte, Brazil',
          mini_bio:
            "I'm a Brazilian-based photographer using my skills to spread awareness about rainforest conservation efforts in my beautiful country.",
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'ms@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 60
          // id: '146',
          sub: 'auth0|5eb1a4186b69bc0c12f7f0aa',
          email: 'fhdasjfhas@jkdasflds.com',
          profile_image: '',
          created_at: '2020-05-05 12:36:40.155663-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'fhdasjfhas@jkdasflds.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 61
          // id: '149',
          sub: 'auth0|5eb1e73454b14c0c127aaac8',
          email: 'hello@hello.com',
          profile_image: '',
          created_at: '2020-05-05 17:23:01.508532-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'hello@hello.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 62
          // id: '150',
          sub: 'auth0|5eb1f7196b69bc0c12f90e44',
          email: 'callahan@callahan.com',
          profile_image: '',
          created_at: '2020-05-05 18:31:07.367034-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'callahan@callahan.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 63
          // id: '151',
          sub: 'auth0|5e2b1e0a100cfd0e95cec91d',
          email: 'jessica@keyconservation.org',
          profile_image: '',
          created_at: '2020-05-05 19:43:01.867515-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jessica@keyconservation.org':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 64
          // id: '164',
          sub: 'auth0|5eb5c55a6b69bc0c120492ab',
          email: 'mikecallahan@callahan.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-08 15:47:35.614393-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'mikecallahan@callahan.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 65
          // id: '165',
          sub: 'auth0|5eb98649db88fb0c7a458200',
          email: 'rmchado@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-11 12:07:40.005895-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'rmchado@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 66
          // id: '148',
          sub: 'auth0|5eb1e0d554b14c0c127a9777',
          email: 'jsjsj@djdjm.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1589312843217_photo.jpg',
          created_at: '2020-05-05 16:56:39.304976-05',
          location: 'San Diego',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'jsjsj@djdjm.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 67
          // id: '176',
          sub: 'auth0|5ec304647d697c0c718e82c9',
          email: 'leohdus33@yahoo.com',
          profile_image: '',
          created_at: '2020-05-18 16:55:57.908755-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'leohdus33@yahoo.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 68
          // id: '177',
          sub: 'auth0|5ec307637d697c0c718e8e8f',
          email: 'rmchao@gmail.com',
          profile_image: '',
          created_at: '2020-05-18 17:08:42.725829-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'rmchao@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 69
          // id: '162',
          sub: 'auth0|5eb43ad154b14c0c1281a396',
          email: 'email@email.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-07 11:44:14.053564-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'email@email.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 70
          // id: '173',
          sub: 'auth0|5ec2b9709c07a10ce7c65809',
          email: 'h273hdi@yahoo.com',
          profile_image: '',
          created_at: '2020-05-18 11:36:16.181717-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'h273hdi@yahoo.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 71
          // id: '163',
          sub: 'auth0|5eb47f656b69bc0c1200ce7d',
          email: 'daniel-kyman@lambdastudents.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1588967057378_photo.png',
          created_at: '2020-05-07 16:37:32.169128-05',
          location: 'Los Angeles',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'daniel-kyman@lambdastudents.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 72
          // id: '166',
          sub: 'auth0|5eb9fb2851344e2216752c3c',
          email: 'callahanmichaele@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-11 20:26:12.037335-05',
          location: 'Denver, CO',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'callahanmichaele@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 73
          // id: '167',
          sub: 'auth0|5eb9ac494f69e12256fa16fc',
          email: 'leonardo@gmail.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-05-11 20:49:01.127265-05',
          location: 'New York',
          mini_bio: 'Testing!',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'leonardo@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 74
          // id: '168',
          sub: 'auth0|5eba018f51344e22167540e2',
          email: 'theleopard@gmail.com',
          profile_image: '',
          created_at: '2020-05-11 20:53:35.63827-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'theleopard@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 75
          // id: '175',
          sub: 'auth0|5ec302d37e70e60c683c6cf4',
          email: 'development+ews@keyconservation.org',
          profile_image: '',
          created_at: '2020-05-18 16:49:23.078557-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'ews@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 76
          // id: '14',
          sub: 'auth0|5e593a74e467971787ca20af',
          email: 'anothertest@org.com',
          profile_image:
            'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
          created_at: '2020-02-28 10:14:12.932603-06',
          location: 'California',
          mini_bio: 'Dedicated to Sylvester',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'conservationist',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 11,
          full_text_weighted: "'anothertest@org.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 77
          // id: '178',
          sub: 'auth0|5ec3082fa535a90c61a54fc0',
          email: 'derrickha32@bmail.com',
          profile_image: '',
          created_at: '2020-05-18 17:12:04.507289-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'derrickha32@bmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 78
          // id: '169',
          sub: 'auth0|5eba05d551344e2216754d5a',
          email: 'robot@yahoo.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1589249662230_photo.png',
          created_at: '2020-05-11 21:11:42.659538-05',
          location: 'Test ',
          mini_bio: 'Hi!!!',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'robot@yahoo.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 79
          // id: '170',
          sub: 'auth0|5eba0bd351344e2216755e80',
          email: 'hehehshs@yahoo.com',
          profile_image: '',
          created_at: '2020-05-11 21:37:23.282632-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'hehehshs@yahoo.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 80
          // id: '179',
          sub: 'auth0|5ec30a6c7d697c0c718e99c9',
          email: 'hdiwhd73@gmail.com',
          profile_image: '',
          created_at: '2020-05-18 17:21:40.425861-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'hdiwhd73@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 81
          // id: '128',
          sub: 'auth0|5e8e14ad9133570c71dfbd71',
          email: 'development+lk@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1590527331234_photo.png',
          created_at: '2020-04-08 13:15:44.809674-05',
          location: 'Nashville, Tennessee',
          mini_bio:
            "I'm a frog obsessed? remote software developer that's currently road tripping across the U.S. visiting all of the national parks!o",
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'develop':1A 'lk@keyconservation.org':2A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 82
          // id: '171',
          sub: 'auth0|5ebae2044e6c6e0c625c1925',
          email: 'hector4444@icloud.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1589306025226_photo.png',
          created_at: '2020-05-12 12:51:22.570847-05',
          location: 'Washington',
          mini_bio: 'Hello',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'hector4444@icloud.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 83
          // id: '174',
          sub: 'auth0|5ec2fda2a535a90c61a526e1',
          email: 'theshwudhwdheu@gmail.com',
          profile_image: '',
          created_at: '2020-05-18 16:27:04.230721-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'theshwudhwdheu@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 84
          // id: '172',
          sub: 'auth0|5ec296429c07a10ce7c5c1f8',
          email: 'freddy837274@gmail.com',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1589810924694_photo.png',
          created_at: '2020-05-18 09:06:04.975631-05',
          location: 'NYC',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'freddy837274@gmail.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 85
          // id: '181',
          sub: 'auth0|5ec314227d697c0c718eccdc',
          email: 'leo@yahoo.com',
          profile_image: '',
          created_at: '2020-05-18 18:03:03.344795-05',
          location: '',
          mini_bio: '',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: '',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'leo@yahoo.com':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
        {
          // newid: 86
          // id: '139',
          sub: 'auth0|5e430dc326001c0ca75ff55b',
          email: 'megan@keyconservation.org',
          profile_image:
            'https://keyconservation.s3.us-west-1.amazonaws.com/files/1590724868349_photo.jpg',
          created_at: '2020-05-05 12:34:35.836092-05',
          location: 'San Diego, California',
          mini_bio:
            'Wildlife biologist, optimist, founder and director of Key Conservation.',
          species_and_habitats: '',
          twitter: '',
          facebook: '',
          instagram: 'https://www.instagram.com/keyconservation/',
          phone_number: '',
          roles: 'supporter',
          admin: 'f',
          is_deactivated: 'f',
          deactivated_at: '',
          strikes: 0,
          full_text_weighted: "'megan@keyconservation.org':1A",
          accepting_help_requests: 'f',
          total_stars: '',
          total_reviews: '',
        },
      ]);
    });
};
